// Please DO NOT use the addresses generated by this 12-word mnemonic.
// You could lose all your funds. Use these only for the purpose of this test.
// By proceeding, you acknowledge that you are fully responsible for any potential consequences of using these keys in a live environment or mainnet.
export const mnemonic =
  "trap suffer brother common elevator arctic endorse two lounge window master filter";
